<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Setting extends Model implements HasMedia
{
    use  InteractsWithMedia;

    protected $fillable = [
        'key',
        'title',
        'content',
        'phone',
        'address'
    ];

    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('logo')
            ->useDisk('settings')
            ->singleFile();

        $this->addMediaCollection('favicon')
            ->useDisk('settings')
            ->singleFile();

        $this->addMediaCollection('settings')
            ->useDisk('settings');
    }

    public static function getByKey($key, $titleOrContent = '')
    {
        if (in_array($key, ['logo', 'favicon'])) {
            return Cache::rememberForever('setting-' . $key, function () use ($key) {
                return self::where('key', $key)->first()?->getFirstMediaUrl($key);
            });
        }

        return Cache::rememberForever('setting-' . $key . '-' . $titleOrContent, function () use ($key, $titleOrContent) {
            return self::where('key', $key)->first()?->$titleOrContent;
        });
    }

    public static function getImage($key)
    {
        return Cache::rememberForever('setting-' . $key, function () use ($key) {
            return self::where('key', $key)->first()?->getFirstMediaUrl($key);
        });


    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saved(function (Model $model) {
            Cache::forget('setting-' . $model->key);
            Cache::forget('setting-' . $model->key . '-' . 'title');
            Cache::forget('setting-' . $model->key . '-' . 'content');
        });

        static::deleted(function (Model $model) {
            Cache::forget('setting-' . $model->key);
            Cache::forget('setting-' . $model->key . '-' . 'title');
            Cache::forget('setting-' . $model->key . '-' . 'content');
        });
    }
}
