<?php

namespace App\Models;

use App\Enums\WorkingDays;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Cache;

class WorkingHour extends Model
{
    use HasFactory;

    protected $fillable = [
        'day',
        'from',
        'to',
    ];

//    protected $casts = [
//        'day' => 'string',
//        'from' => 'datetime:h A',
//        'to' => 'datetime:h A',
//    ];

    protected $casts = [
        'day' => 'string',
        'from' => 'string',
        'to' => 'string',
    ];

    public function scopeOffDays($query)
    {
        return Cache::rememberForever('off-days', function () use ($query) {
//            $this->where('from', null)->where('to', null)
            return $query->where('from', null)->where('to', null)->pluck('day')->toArray();
        });
    }

    public function scopeWorkingDays($query)
    {
        return Cache::rememberForever('working-days', function () use ($query) {
            return $query->where('from', '!=', null)->where('to', '!=', null)->get();
        });
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::saved(function () {
            Cache::forget('off-days');
            Cache::forget('working-days');
        });

        static::deleted(function () {
            Cache::forget('off-days');
            Cache::forget('working-days');
        });
    }
}
